# Generated by Django 3.0.8 on 2020-07-12 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bright', '0003_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Usertoken',
        ),
    ]
